### ISSUE TITLE
Applying `/disguise <entity> as player` repeatedly can result in client side errors and invisible mobs

### ISSUE THREAD

**Issue by James103** [samolego/MobDisguises#17]
When you run `/disguise <entity> as player` (or variants thereof) multiple times, you will eventually get the following error:

<details>

<summary> [15:12:47] [Render thread/FATAL]: Error executing task on Client </summary>
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_640.method_2966()" because the return value of "net.minecraft.class_634.method_2871(java.util.UUID)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.37) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onPlayerSpawn(ClientPlayNetworkHandler:472) ~[?:?]
	at net.minecraft.network.packet.s2c.play.PlayerSpawnS2CPacket.apply(PlayerSpawnS2CPacket:52) ~[?:?]
	at net.minecraft.network.packet.s2c.play.PlayerSpawnS2CPacket.apply(PlayerSpawnS2CPacket:10) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.class_2600$$Lambda$6797/0x0000000028823158.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1075) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

</details>

System Details: [system.txt](https://github.com/samolego/MobDisguises/files/7288956/system.txt)

**Comment by maxheyn** [comment]
I have not experienced any clientside errors but on the second `disguise @e[...] as player` I do get an invisible mob. Disguising it as something other than a player seems to fix it though. The skin still does not apply though, but that is another bug report.
