### ISSUE TITLE
/disguise [entity] clear  Invalid Player Data

### ISSUE THREAD

**Issue by WachumaFox** [samolego/MobDisguises#19]
[07:00:05] [Server thread/WARN]: Failed to handle packet for /[IP]
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:530) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:212) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-server.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bgl000$modifiedRunLoop(MinecraftServer.java:4390) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5864()" because "this.disguiselib$disguiseEntity" is null
	at net.minecraft.class_1297.handler$bfd000$postTick(class_1297.java:8898) ~[intermediary-server.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:445) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2308) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:466) ~[intermediary-server.jar:?]
	... 10 more
[07:00:05] [Server thread/INFO]: [Nicknamed Username] lost connection: Internal server error
[07:00:05] [Server thread/INFO]: PoIarisXD left the game
[07:00:05] [Server thread/INFO]: Disconnecting client [Nicknamed Username]
[07:00:26] [User Authenticator #4/INFO]: UUID of player PoIarisXD is 227f9d79-4bb3-4fd6-bc84-c1464fa78bf5
[07:00:26] [Server thread/INFO]: com.mojang.authlib.GameProfile@1ffe87c7[id=227f9d79-4bb3-4fd6-bc84-c1464fa78bf5,name=PoIarisXD,properties={textures=[com.mojang.authlib.properties.Property@255d393a]},legacy=false] (/[IP]) lost connection: Invalid player data
[07:00:26] [Server thread/WARN]: handleDisconnection() called twice

The player is unable to connect back now, it continues to say "Invalid player data" when attempting to join!

Mod list: 
![image](https://user-images.githubusercontent.com/53717728/139634318-16dc72be-9487-4b1a-92ff-9751dd8dddb7.png)
I wonder if this isn't part of Drogtor the Nickinator messing something up? 
Fabric Version: 0.11.7
Fabric Api: 0.40.1+1.17.jar

**Comment by samolego** [comment]
Please install the latest version of disguiselib
