### ISSUE TITLE
invalid player data

### ISSUE THREAD

**Issue by NishilJ** [samolego/MobDisguises#22]
I was clearing my disguise then this happened and corrupted my player data.

```
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:543) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:213) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbg000$modifiedRunLoop(MinecraftServer.java:2856) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5864()" because "this.disguiselib$disguiseEntity" is null
	at net.minecraft.class_1297.handler$zim000$postTick(class_1297.java:5404) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:453) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2311) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.redirect$zih000$fixUpdateSuppressionCrashPlayerTick(class_3222.java:2743) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:479) ~[server-intermediary.jar:?]
	... 10 more
[14:58:59] [Server thread/INFO]: SLGG lost connection: Internal server error
[14:58:59] [Server thread/INFO]: SLGG left the game

[14:59:48] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3244.method_14364(net.minecraft.class_2596)" because "player.field_13987" is null
	at net.minecraft.class_1297.disguiselib$sendProfileUpdates(class_1297.java:5341) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.setGameProfile(class_1297.java:5274) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.handler$zim000$fromTag(class_1297.java:5455) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1762) ~[server-intermediary.jar:?]
	at net.minecraft.class_29.method_261(class_29.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14600(class_3324.java:352) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$zlg000$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbg000$modifiedRunLoop(MinecraftServer.java:2856) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[14:59:48] [Server thread/INFO]: com.mojang.authlib.GameProfile@44c141fa[id=92216aaf-bcd2-38cf-bd3b-ff6cdb4d2bc4,name=SLGG,properties={},legacy=false] (/98.156.169.253:64426) lost connection: Invalid player data
[14:59:48] [Server thread/WARN]: handleDisconnection() called twice
```

**Comment by NishilJ** [comment]
this is on 1.18.1

**Comment by samolego** [comment]
seems like sth. was expecting you to still be disguised ... thanks for report.
