### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by ghost** [samolego/MobDisguises#28]
Hi I'm trying to use mobdisguises on minecraft 1.19.3 with quilt-loader. When I start the server up I get a `java.lang.NoClassDefFoundError`. Here is the full log:

```
Starting org.quiltmc.loader.impl.game.minecraft.BundlerClassPathCapture
[17:01:30] [INFO] [Quilt Loader/GameProvider]: Loading Minecraft 1.19.3 with Quilt Loader 0.17.11
[17:01:30] [INFO] [Quilt Loader/Mappings]: Loading mappings: jar:file:/home/rikvde/Documents/HobbyServer/libraries/net/fabricmc/intermediary/1.19.3/intermediary-1.19.3.jar!/mappings/mappings.tiny
[17:01:31] [main/INFO]: Loading Minecraft 1.19.3 with Quilt Loader 0.17.11
[17:01:31] [main/INFO]: Loading mappings: jar:file:/home/rikvde/Documents/HobbyServer/libraries/net/fabricmc/intermediary/1.19.3/intermediary-1.19.3.jar!/mappings/mappings.tiny
[17:01:31] [ForkJoinPool-1-worker-2/WARN]: Warnings for mod "jei"'s mod json:
- Version 12.1.1.13 has more than 3 version components, which may not be fully supported. "version" at  at line 4 column 25 path $.version
[17:01:32] [main/INFO]: Loading 119 mods:
| Index | Mod                                            | ID                                                    | Version                     |
|------:|------------------------------------------------|-------------------------------------------------------|-----------------------------|
|     3 | Alternate Current                              | alternate-current                                     | 1.4.0                       |
|   100 | Axes Are Weapons                               | axesareweapons                                        | 1.6.5                       |
|    22 | Carpet Fixes                                   | carpet-fixes                                          | 1.19.3-1.13.0               |
|    96 | Carpet Mod                                     | carpet                                                | 1.4.93                      |
|    26 | Carpet TIS Addition                            | carpet-tis-addition                                   | 1.44.2                      |
|     0 | Carpet-AutoCraftingTable                       | carpet-autocraftingtable                              | 1.4.57                      |
|    68 | Cloth Config v9                                | cloth-config                                          | 9.0.94                      |
|    13 | Config to Brigadier                            | config2brigadier                                      | 1.2.1                       |
|    70 | Debugify                                       | debugify                                              | 1.19.3+1.0                  |
|    17 | Disguise Library                               | disguiselib                                           | 1.3.3                       |
|    16 | Egg Of Capitalism                              | egg-of-capitalism                                     | 3.1                         |
|    80 | Fast Load                                      | fastload                                              | 2.6.11                      |
|   114 | FerriteCore                                    | ferritecore                                           | 5.1.0                       |
|    63 | Infinity Fix                                   | infinityfix                                           | 1.19.x-1.0.2+1.19.3         |
|    83 | Just Enough Items                              | jei                                                   | 12.1.1.13                   |
|    12 | Krypton                                        | krypton                                               | 0.2.1                       |
|    21 | LazyDFU                                        | lazydfu                                               | 0.1.3                       |
|    10 | Ledger                                         | ledger                                                | 1.2.6                       |
|   102 | Minecraft                                      | minecraft                                             | 1.19.3                      |
|   117 | MixinTrace                                     | mixintrace                                            | 1.1.1+1.17                  |
|    15 | Mob Disguises                                  | mobdisguises                                          | 1.1.0                       |
|    33 | OpenJDK 64-Bit Server VM                       | java                                                  | 17                          |
|    51 | Packet Tweaker                                 | packet_tweaker                                        | 0.3.0+1.18.2                |
|   105 | Plasmo Voice                                   | plasmo_voice                                          | 1.2.19                      |
|   118 | Quilt Advancement API                          | quilt_advancement                                     | 4.0.0-beta.10+1.19.3        |
|    58 | Quilt Base API                                 | quilt_base                                            | 4.0.0-beta.10+1.19.3        |
|    73 | Quilt Biome API                                | quilt_biome                                           | 4.0.0-beta.10+1.19.3        |
|   115 | Quilt Block Content Registry API               | quilt_block_content_registry                          | 4.0.0-beta.10+1.19.3        |
|    52 | Quilt Block Entity API                         | quilt_block_entity                                    | 4.0.0-beta.10+1.19.3        |
|    41 | Quilt Block Extensions API                     | quilt_block_extensions                                | 4.0.0-beta.10+1.19.3        |
|   103 | Quilt Chat API                                 | quilt_chat                                            | 4.0.0-beta.10+1.19.3        |
|    38 | Quilt Command API                              | quilt_command                                         | 4.0.0-beta.10+1.19.3        |
|    71 | Quilt Crash Info                               | quilt_crash_info                                      | 4.0.0-beta.10+1.19.3        |
|    45 | Quilt Dimension API                            | quilt_dimension                                       | 4.0.0-beta.10+1.19.3        |
|    59 | Quilt Entity API                               | quilt_entity                                          | 4.0.0-beta.10+1.19.3        |
|   104 | Quilt Entity Events                            | quilt_entity_events                                   | 4.0.0-beta.10+1.19.3        |
|    48 | Quilt Entity Networking API                    | quilt_entity_networking                               | 4.0.0-beta.10+1.19.3        |
|    31 | Quilt Item Content Registry API                | quilt_item_content_registry                           | 4.0.0-beta.10+1.19.3        |
|    62 | Quilt Item Extension API                       | quilt_item_extension                                  | 4.0.0-beta.10+1.19.3        |
|    29 | Quilt Item Setting API                         | quilt_item_setting                                    | 4.0.0-beta.10+1.19.3        |
|    84 | Quilt Kotlin Libraries                         | qkl                                                   | 1.1.0                       |
|    75 | Quilt Kotlin Libraries: Core                   | qkl_core                                              | 1.1.0                       |
|   116 | Quilt Kotlin Libraries: Library                | qkl_library                                           | 1.1.0                       |
|   106 | Quilt Lifecycle Events                         | quilt_lifecycle_events                                | 4.0.0-beta.10+1.19.3        |
|    76 | Quilt Loader                                   | quilt_loader                                          | 0.17.11                     |
|    36 | Quilt Multipart Entity API                     | quilt_entity_multipart                                | 4.0.0-beta.10+1.19.3        |
|    88 | Quilt Networking                               | quilt_networking                                      | 4.0.0-beta.10+1.19.3        |
|    60 | Quilt Points of Interest                       | quilt_points_of_interest                              | 4.0.0-beta.10+1.19.3        |
|    93 | Quilt Recipe API                               | quilt_recipe                                          | 4.0.0-beta.10+1.19.3        |
|    82 | Quilt Registry API                             | quilt_registry                                        | 4.0.0-beta.10+1.19.3        |
|    69 | Quilt Registry Entry Attachment                | quilt_registry_entry_attachment                       | 4.0.0-beta.10+1.19.3        |
|    85 | Quilt Resource Loader                          | quilt_resource_loader                                 | 4.0.0-beta.10+1.19.3        |
|   108 | Quilt Status Effect API                        | quilt_status_effect                                   | 4.0.0-beta.10+1.19.3        |
|    98 | Quilt Surface Rule API                         | quilt_surface_rule                                    | 4.0.0-beta.10+1.19.3        |
|    86 | Quilt Tags API                                 | quilt_tags                                            | 4.0.0-beta.10+1.19.3        |
|    99 | Quilt Tooltip API                              | quilt_tooltip                                         | 4.0.0-beta.10+1.19.3        |
|    50 | Quilt Vehicle API                              | quilt_vehicle                                         | 4.0.0-beta.10+1.19.3        |
|    54 | Quilt Villager API                             | quilt_villager                                        | 4.0.0-beta.10+1.19.3        |
|    89 | Quilted Fabric API                             | quilted_fabric_api                                    | 5.0.0-beta.4+0.73.0-1.19.3  |
|    67 | Quilted Fabric API Base                        | quilted_fabric_api_base                               | 5.0.0-beta.4+0.73.0-1.19.3  |
|    78 | Quilted Fabric API Lookup API (v1)             | quilted_fabric_api_lookup_api_v1                      | 5.0.0-beta.4+0.73.0-1.19.3  |
|    64 | Quilted Fabric Biome API (v1)                  | quilted_fabric_biome_api_v1                           | 5.0.0-beta.4+0.73.0-1.19.3  |
|   109 | Quilted Fabric Block API (v1)                  | quilted_fabric_block_api_v1                           | 5.0.0-beta.4+0.73.0-1.19.3  |
|    44 | Quilted Fabric Command API (v1)                | quilted_fabric_command_api_v1                         | 5.0.0-beta.4+0.73.0-1.19.3  |
|    46 | Quilted Fabric Command API (v2)                | quilted_fabric_command_api_v2                         | 5.0.0-beta.4+0.73.0-1.19.3  |
|    43 | Quilted Fabric Commands (v0)                   | quilted_fabric_commands_v0                            | 5.0.0-beta.4+0.73.0-1.19.3  |
|    56 | Quilted Fabric Containers (v0)                 | quilted_fabric_containers_v0                          | 5.0.0-beta.4+0.73.0-1.19.3  |
|   111 | Quilted Fabric Content Registries (v0)         | quilted_fabric_content_registries_v0                  | 5.0.0-beta.4+0.73.0-1.19.3  |
|    57 | Quilted Fabric Convention Tags API (v1)        | quilted_fabric_convention_tags_api_v1                 | 5.0.0-beta.4+0.73.0-1.19.3  |
|    37 | Quilted Fabric Crash Report Info (v1)          | quilted_fabric_crash_report_info_v1                   | 5.0.0-beta.4+0.73.0-1.19.3  |
|    72 | Quilted Fabric Data Generation API (v1)        | quilted_fabric_data_generation_api_v1                 | 5.0.0-beta.4+0.73.0-1.19.3  |
|    90 | Quilted Fabric Dimensions API (v1)             | quilted_fabric_dimensions_v1                          | 5.0.0-beta.4+0.73.0-1.19.3  |
|    55 | Quilted Fabric Entity Events (v1)              | quilted_fabric_entity_events_v1                       | 5.0.0-beta.4+0.73.0-1.19.3  |
|    97 | Quilted Fabric Events Interaction (v0)         | quilted_fabric_events_interaction_v0                  | 5.0.0-beta.4+0.73.0-1.19.3  |
|    66 | Quilted Fabric Events Lifecycle (v0)           | quilted_fabric_events_lifecycle_v0                    | 5.0.0-beta.4+0.73.0-1.19.3  |
|    39 | Quilted Fabric Game Rule API (v1)              | quilted_fabric_game_rule_api_v1                       | 5.0.0-beta.4+0.73.0-1.19.3  |
|    61 | Quilted Fabric Item API (v1)                   | quilted_fabric_item_api_v1                            | 5.0.0-beta.4+0.73.0-1.19.3  |
|    32 | Quilted Fabric Item Group API (v1)             | quilted_fabric_item_group_api_v1                      | 5.0.0-beta.4+0.73.0-1.19.3  |
|    77 | Quilted Fabric Lifecycle Events (v1)           | quilted_fabric_lifecycle_events_v1                    | 5.0.0-beta.4+0.73.0-1.19.3  |
|    95 | Quilted Fabric Loot API (v2)                   | quilted_fabric_loot_api_v2                            | 5.0.0-beta.4+0.73.0-1.19.3  |
|    30 | Quilted Fabric Loot Tables (v1)                | quilted_fabric_loot_tables_v1                         | 5.0.0-beta.4+0.73.0-1.19.3  |
|    65 | Quilted Fabric Message API (v1)                | quilted_fabric_message_api_v1                         | 5.0.0-beta.4+0.73.0-1.19.3  |
|   113 | Quilted Fabric Mining Level API (v1)           | quilted_fabric_mining_level_api_v1                    | 5.0.0-beta.4+0.73.0-1.19.3  |
|    40 | Quilted Fabric Networking (v0)                 | quilted_fabric_networking_v0                          | 5.0.0-beta.4+0.73.0-1.19.3  |
|    35 | Quilted Fabric Networking API (v1)             | quilted_fabric_networking_api_v1                      | 5.0.0-beta.4+0.73.0-1.19.3  |
|    53 | Quilted Fabric Object Builder API (v1)         | quilted_fabric_object_builder_api_v1                  | 5.0.0-beta.4+0.73.0-1.19.3  |
|   112 | Quilted Fabric Particles (v1)                  | quilted_fabric_particles_v1                           | 5.0.0-beta.4+0.73.0-1.19.3  |
|   110 | Quilted Fabric Recipe API (v1)                 | quilted_fabric_recipe_api_v1                          | 5.0.0-beta.4+0.73.0-1.19.3  |
|   101 | Quilted Fabric Registry Sync (v0)              | quilted_fabric_registry_sync_v0                       | 5.0.0-beta.4+0.73.0-1.19.3  |
|    49 | Quilted Fabric Rendering Data Attachment (v1)  | quilted_fabric_rendering_data_attachment_v1           | 5.0.0-beta.4+0.73.0-1.19.3  |
|    81 | Quilted Fabric Rendering Fluids (v1)           | quilted_fabric_rendering_fluids_v1                    | 5.0.0-beta.4+0.73.0-1.19.3  |
|    42 | Quilted Fabric Resource Conditions API (v1)    | quilted_fabric_resource_conditions_api_v1             | 5.0.0-beta.4+0.73.0-1.19.3  |
|   107 | Quilted Fabric Resource Loader (v0)            | quilted_fabric_resource_loader_v0                     | 5.0.0-beta.4+0.73.0-1.19.3  |
|    91 | Quilted Fabric Screen Handler API (v1)         | quilted_fabric_screen_handler_api_v1                  | 5.0.0-beta.4+0.73.0-1.19.3  |
|    87 | Quilted Fabric Transfer API (v1)               | quilted_fabric_transfer_api_v1                        | 5.0.0-beta.4+0.73.0-1.19.3  |
|    79 | Quilted Fabric Transitive Access Wideners (v1) | quilted_fabric_transitive_access_wideners_v1          | 5.0.0-beta.4+0.73.0-1.19.3  |
|    74 | Right-Click-Harvest                            | right-click-harvest                                   | 1.2.0                       |
|    34 | Server Translations API                        | server_translations_api                               | 1.4.18+1.19.2               |
|    47 | SilkSpawners                                   | silkspawners                                          | 1.1.2                       |
|    92 | Starlight                                      | starlight                                             | 1.1.1+fabric.ae22326        |
|     6 | Taterzens                                      | taterzens                                             | 1.11.2                      |
|     8 | atomicfu-jvm                                   | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.19.0                      |
|    23 | cloth-basic-math                               | cloth-basic-math                                      | 0.6.1                       |
|    27 | conditional mixin                              | conditional-mixin                                     | 0.3.2                       |
|    18 | fabric-permissions-api                         | fabric-permissions-api-v0                             | 0.2-SNAPSHOT                |
|    11 | kotlin-reflect                                 | org_jetbrains_kotlin_kotlin-reflect                   | 1.8.0                       |
|     4 | kotlin-stdlib                                  | org_jetbrains_kotlin_kotlin-stdlib                    | 1.8.0                       |
|     5 | kotlin-stdlib-jdk7                             | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.8.0                       |
|     7 | kotlin-stdlib-jdk8                             | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.8.0                       |
|    24 | kotlinx-coroutines-core-jvm                    | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                       |
|     9 | kotlinx-coroutines-jdk8                        | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                       |
|    19 | kotlinx-datetime-jvm                           | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                       |
|    28 | kotlinx-serialization-cbor-jvm                 | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.4.1                       |
|    20 | kotlinx-serialization-core-jvm                 | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.4.1                       |
|     1 | kotlinx-serialization-json-jvm                 | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.4.1                       |
|    94 | memory Leak Fix                                | memoryleakfix                                         | 1.19.3-0.7.0                |
|     2 | mixinextras                                    | com_github_llamalad7_mixinextras                      | 0.1.1                       |
|    25 | sgui                                           | sgui                                                  | 1.2.0+1.19.3                |
|    14 | velocity-native                                | com_velocitypowered_velocity-native                   | 3.1.2-SNAPSHOT              |
|------:|------------------------------------------------|-------------------------------------------------------|-----------------------------|
[17:01:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/rikvde/Documents/HobbyServer/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Quilt Env=SERVER
[17:01:32] [main/INFO]: Compatibility level set to JAVA_16
[17:01:32] [main/INFO]: Compatibility level set to JAVA_17
[17:01:32] [main/INFO]: Preloading Debugify
[17:01:32] [main/WARN]: Reference map 'plasmovoice-fabric-refmap.json' for plasmovoice.mixins.json could not be read. If this is a development environment you can ignore this message
[17:01:33] [main/WARN]: Error loading class: net/minecraft/class_7494 (java.lang.ClassNotFoundException: net/minecraft/class_7494)
[17:01:33] [main/WARN]: Force disabled MC-135971 because it's conflicting with: carpet
[17:01:35] [main/WARN]: Method overwrite conflict for method_5800 in carpet.mixins.json:ItemEntityMixin from mod carpet, previously written by carpetfixes.mixins.itemFixes.ItemEntity_lightningKillsDropsMixin. Skipping method.
[17:01:36] [main/WARN]: @Redirect conflict. Skipping debugify.mixins.json:basic.mc160095.CactusBlockMixin from mod debugify->@Redirect::replaceBlockState(Lnet/minecraft/class_4538;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; with priority 1000, already redirected by carpet-fixes.mixins.json:blockFixes.CactusBlock_movingBlockMixin from mod carpet-fixes->@Redirect::getCorrectBlockStateIfMovingPiston(Lnet/minecraft/class_4538;Lnet/minecraft/class_2338;)Lnet/minecraft/class_2680; with priority 1000
[17:01:38] [main/INFO]: Building unoptimized datafixer
[17:01:40] [main/INFO]: [Quilt Command] Networking support is enabled
[17:01:41] [main/INFO]: Compression will use libdeflate (Linux x86_64), encryption will use OpenSSL 1.1.x (Linux x86_64)
[17:01:41] [main/INFO]: Loaded C2B lib.
[17:01:41] [main/INFO]: DisguiseLib loaded.
[17:01:42] [TISCM Mapping/INFO]: Yarn mapping file yarn-1.19.3+build.5-v2.tiny loaded
[17:01:42] [main/INFO]: Enabled 34 bug fixes: [MC-2025, MC-7569, MC-14923, MC-30391, MC-31819, MC-69216, MC-72151, MC-88371, MC-89146, MC-90084, MC-93018, MC-100991, MC-119417, MC-119754, MC-121706, MC-121903, MC-124117, MC-129909, MC-132878, MC-135971, MC-155509, MC-160095, MC-179072, MC-183990, MC-193343, MC-199467, MC-200418, MC-206922, MC-214147, MC-215530, MC-223153, MC-224729, MC-231743, MC-232869]
[17:01:42] [main/INFO]: Successfully Debugify'd your game!
[17:01:42] [main/INFO]: [STDOUT]: net.minecraft.class_2248
[17:01:42] [main/INFO]: DEBUG: FALSE
[17:01:42] [main/INFO]: PREGEN_CHUNK_RADIUS: 5
[17:01:42] [main/INFO]: PREGEN_CHUNK_AREA: 121
[17:01:42] [main/INFO]: Initializing Ledger 1.2.6
[17:01:43] [main/INFO]: Krypton is now accelerating your Minecraft server's networking stack 🚀
[17:01:43] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:01:45] [main/ERROR]: Minecraft has crashed!
org.quiltmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/minecraft/class_2188
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:425) ~[quilt-loader-0.17.11.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) ~[quilt-loader-0.17.11.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) ~[quilt-loader-0.17.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) ~[quilt-loader-0.17.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2188
	at org.samo_lego.mobdisguises.command.DisguiseCommand.register(DisguiseCommand.java:42) ~[mobdisguises-1.1.0-fabric.jar:?]
	at org.samo_lego.mobdisguises.fabric.MobDisguisesFabric.lambda$onInitialize$0(MobDisguisesFabric.java:25) ~[mobdisguises-1.1.0-fabric.jar:?]
	at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:46) ~[fabric-command-api-v2-5.0.0-beta.4+0.73.0-1.19.3.jar-91d42a15-6f5e-4a67-8ec3-1bf1d236e13c-nested.jar:?]
	at org.quiltmc.qsl.command.api.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:39) ~[command-4.0.0-beta.10+1.19.3.jar-ec5cabfa-0617-4f39-bc15-7ec63b0659b7-nested.jar:?]
	at net.minecraft.class_2170.handler$cgg000$addQuiltCommands(class_2170.java:1566) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:942) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:936) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:150) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.11.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2188
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159) ~[quilt-loader-0.17.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.samo_lego.mobdisguises.command.DisguiseCommand.register(DisguiseCommand.java:42) ~[mobdisguises-1.1.0-fabric.jar:?]
	at org.samo_lego.mobdisguises.fabric.MobDisguisesFabric.lambda$onInitialize$0(MobDisguisesFabric.java:25) ~[mobdisguises-1.1.0-fabric.jar:?]
	at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:46) ~[fabric-command-api-v2-5.0.0-beta.4+0.73.0-1.19.3.jar-91d42a15-6f5e-4a67-8ec3-1bf1d236e13c-nested.jar:?]
	at org.quiltmc.qsl.command.api.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:39) ~[command-4.0.0-beta.10+1.19.3.jar-ec5cabfa-0617-4f39-bc15-7ec63b0659b7-nested.jar:?]
	at net.minecraft.class_2170.handler$cgg000$addQuiltCommands(class_2170.java:1566) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:942) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:936) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:150) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.11.jar:?]
	... 7 more

```

**Comment by samolego** [comment]
Yeah, this hasn't been updated in a while 😅

**Comment by cootshk** [comment]
I have the same error
